In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

# Intro to Neural Networks

## Demos

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
A = np.random.uniform(size = (200, 500))
B = np.random.uniform(size = (500, 200))

In [5]:
tf.matmul(A, B)

<tf.Tensor: shape=(200, 200), dtype=float64, numpy=
array([[127.24522129, 123.09367397, 123.11675354, ..., 124.3268622 ,
        128.86083907, 132.11287904],
       [123.02809325, 123.52609522, 119.19766634, ..., 121.45162854,
        121.98163823, 128.75521498],
       [117.50754082, 116.60337139, 116.56676013, ..., 117.77602778,
        117.28467566, 122.94939686],
       ...,
       [128.36805345, 127.71596173, 120.30973894, ..., 131.47537736,
        128.81665996, 137.91502215],
       [121.24690387, 120.99482829, 118.72616612, ..., 120.18345776,
        124.99874792, 134.52654949],
       [119.82505325, 121.95549942, 118.43563334, ..., 122.7094102 ,
        121.61850346, 126.90456199]])>

In [6]:
a = np.array([5, 1, 2, 3, 10])
b = np.array([8, -3, 8, 15, 0])

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

[1156   49  784 2601  400]
<class 'numpy.ndarray'>


In [7]:
a = tf.constant([5, 1, 2, 3, 10])
b = tf.constant([8, -3, 8, 15, 0])

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor([1156   49  784 2601  400], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
type(result.numpy())

numpy.ndarray

In [9]:
a = tf.constant(np.array([5, 1, 2, 3, 10]))
b = tf.constant(np.array([8, -3, 8, 15, 0]))

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor([1156   49  784 2601  400], shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
a = tf.constant(5)
b = tf.constant(8)

result = (2 * a + 3 * b) ** 2

print(result)
print(type(result))

tf.Tensor(1156, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [11]:
a = tf.constant(np.array([5, 1, 2, 3, 10]))
b = tf.constant(np.array([8, -3, 8, 15, 0]))

tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1156,   49,  784, 2601,  400])>

In [12]:
tf.reduce_mean([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
tf.reduce_mean(np.random.uniform(size = (10, 10)))

<tf.Tensor: shape=(), dtype=float64, numpy=0.4888455985020832>

In [14]:
tf.keras.backend.clear_session()

In [15]:
income_data = pd.read_csv("./data/adult.data", sep = ", ", engine = "python", header = None)

In [16]:
income_data.columns = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income_class"]

In [17]:
income_data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income_class  
0              2174             0              40  United-States        <=50K  
1                 0             0              13  United-States        <=50K  
2                 0             0              40  United-States        <=50K  
3                 0             0              40  United-States        <=50K  
4                 0             0              40           Cuba        <=50K  
...             ...           ...             ...            ...          ...  
32556             0             0              38  United-States        <=50K  
32557             0             0              40  United-States         >50K  
32558             0             0              40  United-States        <=50K  
32559             0             0              20  United-States        <=50K  
32560         15024             0              40  United-States         >50K  

[32561 rows x 15 columns]

In [18]:
income_attributes, income_target = income_data.drop(columns = ["income_class"]), income_data.income_class

In [21]:
income_attributes = pd.get_dummies(income_attributes)

In [30]:
income_attributes = income_attributes.drop(columns = ["fnlwgt"])

In [49]:
income_target = income_target.replace({"<=50K": 0, ">50K": 1})

In [50]:
income_attributes_train, income_attributes_test, income_target_train, income_target_test = train_test_split(
    income_attributes, income_target, stratify = income_target, test_size = 5000)

In [51]:
income_target_train.value_counts() / len(income_target_train)

0    0.759189
1    0.240811
Name: income_class, dtype: float64

In [52]:
income_target_test.value_counts() / len(income_target_test)

0    0.7592
1    0.2408
Name: income_class, dtype: float64

In [53]:
income_attributes_train

age  education-num  capital-gain  capital-loss  hours-per-week  \
29467   30             13             0             0              45   
19043   30             10             0             0              40   
3478    35             13             0             0              40   
21382   62             14             0             0              50   
24538   32             13             0             0              30   
...    ...            ...           ...           ...             ...   
14725   65             13         10605             0              40   
7757    50             10             0             0              60   
8140    27              9             0             0              50   
17832   66              4             0             0              20   
4184    22             13             0             0              40   

       workclass_?  workclass_Federal-gov  workclass_Local-gov  \
29467            0                      0                    0   
19043            0                      0                    0   
3478             0                      0                    0   
21382            0                      0                    1   
24538            0                      0                    0   
...            ...                    ...                  ...   
14725            1                      0                    0   
7757             0                      0                    0   
8140             0                      0                    0   
17832            0                      0                    1   
4184             0                      0                    0   

       workclass_Never-worked  workclass_Private  ...  \
29467                       0                  1  ...   
19043                       0                  1  ...   
3478                        0                  1  ...   
21382                       0                  0  ...   
24538                       0                  1  ...   
...                       ...                ...  ...   
14725                       0                  0  ...   
7757                        0                  1  ...   
8140                        0                  1  ...   
17832                       0                  0  ...   
4184                        0                  1  ...   

       native-country_Portugal  native-country_Puerto-Rico  \
29467                        0                           0   
19043                        0                           0   
3478                         0                           0   
21382                        0                           0   
24538                        0                           0   
...                        ...                         ...   
14725                        0                           0   
7757                         0                           0   
8140                         0                           0   
17832                        0                           0   
4184                         0                           0   

       native-country_Scotland  native-country_South  native-country_Taiwan  \
29467                        0                     0                      0   
19043                        0                     0                      0   
3478                         0                     0                      0   
21382                        0                     0                      0   
24538                        0                     0                      0   
...                        ...                   ...                    ...   
14725                        0                     0                      0   
7757                         0                     0                      0   
8140                         0                     0                      0   
17832                        0                     0                      0   
4184                         0        

In [35]:
scaller = MinMaxScaler()
income_attributes_train_scalled = scaller.fit_transform(income_attributes_train)
income_attributes_test_scalled = scaller.transform(income_attributes_test)

In [40]:
income_attributes_train_scalled.max(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [41]:
num_attrubutes = income_attributes.shape[1]
num_attrubutes

107

In [64]:
logistic_regression = Sequential([
    Input(shape = (num_attrubutes, )),
    Dense(1, activation = "sigmoid")
], name = "log_reg")

In [65]:
logistic_regression.summary()

Model: "log_reg"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 108       
                                                                 
Total params: 108
Trainable params: 108
Non-trainable params: 0
_________________________________________________________________


In [56]:
logistic_regression.compile(loss = "binary_crossentropy", optimizer = "sgd")

In [63]:
logistic_regression.fit(income_attributes_train, income_target_train, epochs = 99)

Epoch 1/99
862/862 [==============================] - 1s 636us/step - loss: 1501.7423
Epoch 2/99
862/862 [==============================] - 1s 618us/step - loss: 1435.8555
Epoch 3/99
862/862 [==============================] - 1s 635us/step - loss: 1393.4595
Epoch 4/99
862/862 [==============================] - 1s 601us/step - loss: 1376.4418
Epoch 5/99
862/862 [==============================] - 1s 622us/step - loss: 1505.4445
Epoch 6/99
862/862 [==============================] - 1s 617us/step - loss: 2223.0808
Epoch 7/99
862/862 [==============================] - 1s 630us/step - loss: 1410.2860
Epoch 8/99
862/862 [==============================] - 1s 659us/step - loss: 2122.3511
Epoch 9/99
862/862 [==============================] - 1s 631us/step - loss: 1373.9933
Epoch 10/99
862/862 [==============================] - 1s 635us/step - loss: 1343.0771
Epoch 11/99
862/862 [==============================] - 1s 625us/step - loss: 1287.6337
Epoch 12/99
862/862 [==============================]

862/862 [==============================] - 1s 637us/step - loss: 1900.9220
Epoch 96/99
862/862 [==============================] - 1s 618us/step - loss: 1495.5946
Epoch 97/99
862/862 [==============================] - 1s 646us/step - loss: 1499.2208
Epoch 98/99
862/862 [==============================] - 1s 628us/step - loss: 1503.5367
Epoch 99/99
862/862 [==============================] - 1s 640us/step - loss: 1365.6696


In [98]:
nn = Sequential([
    Input(shape = (num_attrubutes, )),
    
    Dense(30, activation = "relu"),
    Dense(20, activation = "relu"),
    Dense(10, activation = "relu"),
    
    Dense(1, activation = "sigmoid")
], name = "nn")

In [99]:
nn.summary()

Model: "nn"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_41 (Dense)            (None, 30)                3240      
                                                                 
 dense_42 (Dense)            (None, 20)                620       
                                                                 
 dense_43 (Dense)            (None, 10)                210       
                                                                 
 dense_44 (Dense)            (None, 1)                 11        
                                                                 
Total params: 4,081
Trainable params: 4,081
Non-trainable params: 0
_________________________________________________________________


In [109]:
nn.compile(loss = "binary_crossentropy", optimizer = "sgd", metrics = ["accuracy"])

In [110]:
nn.fit(income_attributes_train, income_target_train, epochs = 99)

Epoch 1/99
862/862 [==============================] - 1s 812us/step - loss: 1.4925 - accuracy: 0.7577
Epoch 2/99
862/862 [==============================] - 1s 825us/step - loss: 0.5079 - accuracy: 0.7592
Epoch 3/99
862/862 [==============================] - 1s 805us/step - loss: 0.4938 - accuracy: 0.7592
Epoch 4/99
862/862 [==============================] - 1s 800us/step - loss: 0.4807 - accuracy: 0.7592
Epoch 5/99
862/862 [==============================] - 1s 888us/step - loss: 0.4673 - accuracy: 0.7592
Epoch 6/99
862/862 [==============================] - 1s 872us/step - loss: 0.4550 - accuracy: 0.7592
Epoch 7/99
862/862 [==============================] - 1s 868us/step - loss: 0.4432 - accuracy: 0.7592
Epoch 8/99
862/862 [==============================] - 1s 871us/step - loss: 0.4457 - accuracy: 0.7592
Epoch 9/99
862/862 [==============================] - 1s 900us/step - loss: 0.4288 - accuracy: 0.7605
Epoch 10/99
862/862 [==============================] - 1s 908us/step - loss: 0.428

KeyboardInterrupt: 

In [111]:
nn.evaluate(income_attributes_train, income_target_train)

862/862 [==============================] - 1s 654us/step - loss: 0.3933 - accuracy: 0.8068


[0.3933012783527374, 0.806828498840332]

In [112]:
nn.evaluate(income_attributes_test, income_target_test)

157/157 [==============================] - 0s 712us/step - loss: 0.3985 - accuracy: 0.8004


[0.39848995208740234, 0.8004000186920166]